# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cats Table CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cats-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: cats-table-steps
        uses: cats-table-react-ts@v1
      - run: echo "Hellow World"
